# Workflow to build and deploy to your Github Pages repo.

# Remember to add API_TOKEN_GITHUB in repo Settings > Secrets as well!

name: Github Pages Eleventy CI

on:
  # Triggers the workflow on push and pull request events but only for the source branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install dependencies with npm
      - name: Install dependencies
        run: npm i

      # Build the project and add .nojekyll file to supress default behaviour
      - name: Build
        run: |
          npm run build
          touch ./_site/.nojekyll

      # Deploy dist to github pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          publish_dir: ./_site
